version: '3'

services:
  db:
    image: postgres:13
    container_name: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 12
    # volumes:
    #   - postgres_data_django_cms:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: mypassword
    networks:
      - django_cms

networks:
  django_cms:
    driver: bridge

volumes:
  postgres_data_django_cms:
    name: "postgres_data_django_cms"
